### ISSUE TITLE
Can't get it to run using php -S && parse_tmx not working for me

### ISSUE THREAD

**Issue by kaiser-translations** [vekien/QueriaTMX#2]
Hiya,
- I downloaded the repo as a zip, giving me a directory called QueryTMX-main
- I installed php CLI under WLS
- In the above QueriaTMX-main directory, I ran php -S localhost:8000
- I navigated to localhost:8000 and it showed a php server reporting "Not Found The requested resource / was not found on this server."

- I placed tmx files in the tmx directory and ran 'php -d memory_limit=-1 bin/console parse_tmx' from the QueriaTMX-main directory, resulting in 
PHP Warning:  require(/<fullpath>/QueriaTMX-main/vendor/autoload.php): failed to open stream: No such file or directory in <fullpath>/QueriaTMX-main/bin/console on line 11
PHP Fatal error:  require(): Failed opening required '<fullpath>/QueriaTMX-main/vendor/autoload.php' (include_path='.:/usr/share/php') in <fullpath>/QueriaTMX-main/bin/console on line 11

QueriaTMX-main/bin/console has this line:
require dirname(__DIR__).'/vendor/autoload.php';

It's been 15+ years since I last touched php, so I've got no idea how to approach this.

**Comment by vekien** [comment]
I'm going to edit this post as I've updated the repository to include PHP 7.4, the vendor folder with all the composer installed libraries as well as an updated `.env` and new instructions, I've just tested these so they should work!

https://github.com/vekien/QueriaTMX

----

To solve this: 
- https://getcomposer.org/download/
- Download composer, then run `composer install` in the directory of the code.

You should see a `composer.json` file, so you're telling composer to install all the libraries this project uses.

You should be able to then proceed as normal through your current process.
